### ISSUE TITLE
queued RestActions lost on shutdown()

### ISSUE THREAD

**Issue by bantu** [DV8FromTheWorld/JDA#1212]
- [X] I have checked for similar issues.
- [X] I have updated to the [latest JDA version][download].
- [x] I have checked the branches or the maintainers' PRs for upcoming bug fixes.

## Bug Report

The code snippet below does not send all messages to the channel. This is unexpected because https://ci.dv8tion.net/job/JDA/javadoc/net/dv8tion/jda/api/JDA.html#shutdown() says that "Already enqueued RestActions are still going to be executed." The code works correctly, when complete() is used instead of queue().

### Expected Behavior

15 messages (Test0 ... Test14) are sent to the channel.

### Code Example or Reproduction Steps

```java
JDA jda = new JDABuilder("MyToken").build().awaitReady();
Guild guild = jda.getGuildsByName("MyGuild", true).get(0);
TextChannel channel = guild.getTextChannelsByName("MyChannel", true).get(0);
for (int i = 0; i < 15; i++) {
    channel.sendMessage("Test" + i).queue();
}
jda.shutdown();
```

### Exception or Error

N/A

**Comment by MinnDevelopment** [comment]
This should be fixed in 4.1.1_110

**Comment by bantu** [comment]
@MinnDevelopment Thanks for the quick patch. Unfortunately the issue persists using 4.1.1_110.

**Comment by MinnDevelopment** [comment]
Are you sure? I tested your code and it works as expected sending messages from 0 to 14

**Comment by bantu** [comment]
I only see "Test0". I verified that I am actually using 4.1.1_110 by printing the version number. I am open to debugging suggestions.

**Comment by DManstrator** [comment]
I can actually reproduce this on 4.1.1_110.

Code:
```
public class TestBot {
    private final static String TOKEN = "hereToken";
    private final static long CHANNEL_ID = hereChannelId;
    
    public static void main(String[] args) throws LoginException, InterruptedException  {
        JDA jda = new JDABuilder(TOKEN).build().awaitReady();
        TextChannel channel = jda.getTextChannelById(CHANNEL_ID);
        channel.sendMessageFormat("I am on Version %s!", JDAInfo.VERSION).queue();
        for (int i = 0; i < 15; i++) {
            channel.sendMessage("Test" + i).queue();
        }
        jda.shutdown();
    }
}
```
Console-Output:
```
[main] INFO net.dv8tion.jda.api.JDA - Login Successful!
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.internal.requests.WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO net.dv8tion.jda.api.JDA - Finished Loading!
```
Output in my Discord:
```
[9:25 PM] BOT DisscordFunBot: I am on Version 4.1.1_110!
```

Program was instantly terminating after "Finished Loading!" was printed in the console and the bot has send the single message after that (at least the notification appeared after this).

**Comment by MinnDevelopment** [comment]
Same code:

![image](https://user-images.githubusercontent.com/18090140/75716365-560e8800-5ccf-11ea-934d-98dc75832905.png)

**Comment by MinnDevelopment** [comment]
Is it possible that you use a different version of okhttp? In newer versions all the threads by okhttp are daemon which causes the JVM to shutdown. The rate-limiter threads are also daemon by default.

**Comment by DManstrator** [comment]
I don't have many dependencies for this project.

```gradle
dependencies {
    compile 'net.dv8tion:JDA:4.1.1_110'
    //compile 'org.jscience:jscience:4.3.1'
    compile group: 'org.json', name: 'json', version: '20180813'
    testCompile group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25'
}
```
According to my "Project and External Dependencies", I use OkHttp 3.13.0, is that the newest version used by JDA? I don't think that one of the other dependencies uses OkHttp so I don't see how I could have a different / older version.

**Comment by MinnDevelopment** [comment]
From my testing, it works on the JDA provided okhttp version and doesn't work when forcing a newer version with daemon threads.

**Comment by DManstrator** [comment]
Can this be the cause of an older JRE / JDK? My project uses JRE 1.8.0_181. Else I can't explain it tbh.

**Comment by bantu** [comment]
JVM:          11.0.6 (Ubuntu 11.0.6+10-post-Ubuntu-1ubuntu119.10.1)

Dependency Tree:
```
+--- net.dv8tion:JDA:4.1.1_110
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.jetbrains:annotations:16.0.1
|    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.28
|    +--- com.neovisionaries:nv-websocket-client:2.9
|    +--- com.squareup.okhttp3:okhttp:3.13.0
|    |    \--- com.squareup.okio:okio:1.17.2
|    +--- org.apache.commons:commons-collections4:4.1 -> 4.2
|    +--- net.sf.trove4j:trove4j:3.0.3
|    \--- com.fasterxml.jackson.core:jackson-databind:2.10.1
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.10.1
|         \--- com.fasterxml.jackson.core:jackson-core:2.10.1
```

**Comment by MinnDevelopment** [comment]
Try putting `Thread.sleep(30000);` after your call to shutdown.

**Comment by bantu** [comment]
Works for me.

**Comment by DManstrator** [comment]
Also works for me but somehow, the bot goes offline before sending those messages. But it sends it.

**Comment by kantenkugel** [comment]
@DManstrator thats intended. the Websocket is shut down right away, as it is no longer needed

**Comment by bantu** [comment]
@kantenkugel Aren't messages still queued supposed to be sent via the websocket?

**Comment by kantenkugel** [comment]
No, Messages are sent via REST API, the Websocket is mainly for events and status

**Comment by kantenkugel** [comment]
Assuming this issue is closed now?

**Comment by bantu** [comment]
> Assuming this issue is closed now?

I'd suggest to fix this more properly. It would break again anyway as soon as okhttp is updated.

**Comment by kantenkugel** [comment]
Hm. adding a custom thread/waiter to wait for queue emptying would probably break the shutdown contract by possibly waiting minutes

**Comment by DManstrator** [comment]
> I'd suggest to fix this more properly.
I would agree on that. At least I would like to know why it works for Minn but not for us (without that hotfix).

**Comment by MinnDevelopment** [comment]
This should be completely resolved on 4.1.1_116

**Comment by bantu** [comment]
Can not confirm. Behaviour unchanged.

```
+--- net.dv8tion:JDA:4.1.1_116
|    +--- com.google.code.findbugs:jsr305:3.0.2
|    +--- org.jetbrains:annotations:16.0.1
|    +--- org.slf4j:slf4j-api:1.7.25 -> 1.7.28
|    +--- com.neovisionaries:nv-websocket-client:2.9
|    +--- com.squareup.okhttp3:okhttp:3.13.0
|    |    \--- com.squareup.okio:okio:1.17.2
|    +--- org.apache.commons:commons-collections4:4.1 -> 4.2
|    +--- net.sf.trove4j:trove4j:3.0.3
|    \--- com.fasterxml.jackson.core:jackson-databind:2.10.1
|         +--- com.fasterxml.jackson.core:jackson-annotations:2.10.1
|         \--- com.fasterxml.jackson.core:jackson-core:2.10.1
```

**Comment by bantu** [comment]
I have to take that back. I was accidentally executing using JUnit. All good. Thank you.
